# Generated by Django 3.2.18 on 2023-06-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0043_auto_20230606_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.IntegerField()),
                ('canvas_user_id', models.IntegerField()),
                ('sis_user_id', models.CharField(max_length=255)),
                ('sis_login_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
