# Generated by Django 3.2.18 on 2023-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='canvas_course_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
