# Generated by Django 3.2.18 on 2023-06-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_canvas_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='sis_login_id',
            new_name='login_id',
        ),
    ]
