# Generated by Django 3.2.18 on 2023-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_rename_sis_login_id_enrollment_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='page_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='participations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
