# Generated by Django 3.2.18 on 2023-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_auto_20230609_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='average_assignment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
