# Generated by Django 3.2.20 on 2023-08-14 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='I.e. how many students can do this project simultaneously? (normally max 4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number of students'),
        ),
    ]
