# Generated by Django 3.2.22 on 2023-11-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_label'),
        ('projects', '0006_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projecttype', verbose_name='Primary project type'),
        ),
        migrations.AlterField(
            model_name='projectkeyword',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='projectkeyword',
            unique_together={('title', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttype',
            unique_together={('title', 'school')},
        ),
    ]
