# Generated by Django 3.2.22 on 2023-11-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20231102_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
