# Generated by Django 3.2.23 on 2024-03-01 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projecttype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='This must be a nine digit number', regex='^\\d{9}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
