# Generated by Django 3.2.17 on 2023-02-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230202_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='CANVAS_API_TOKEN',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='CANVAS_API_URL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='department',
            name='CANVAS_API_TOKEN',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='CANVAS_API_URL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
