# Generated by Django 3.2.17 on 2023-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_course_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='course_prefix',
        ),
        migrations.AddField(
            model_name='department',
            name='course_prefixes',
            field=models.CharField(blank=True, help_text='This should be a comma separated list, e.g. PHYS,MATH,CHEM', max_length=128, null=True),
        ),
    ]
