# Generated by Django 3.2.20 on 2023-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230202_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='label',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
