# Generated by Django 3.2.18 on 2023-03-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0034_assignment_average_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader', models.CharField(max_length=128)),
                ('graded_count', models.IntegerField()),
                ('graded_at', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
