# Generated by Django 3.2.18 on 2023-03-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemarker',
            name='graded_at',
        ),
    ]
