# Generated by Django 3.2.17 on 2023-02-02 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_remove_assignment_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=128)),
                ('from_value', models.CharField(blank=True, max_length=128, null=True)),
                ('to_value', models.CharField(blank=True, max_length=128, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assignment')),
            ],
        ),
    ]
