# Generated by Django 3.2.17 on 2023-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='request',
            field=models.CharField(choices=[('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CREATE', 'Create')], default='UPDATE', max_length=128),
            preserve_default=False,
        ),
    ]
