# Generated by Django 3.2.17 on 2023-02-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_assignmentlog_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentlog',
            old_name='key',
            new_name='field',
        ),
    ]
