# Generated by Django 3.2.17 on 2023-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20230202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlog',
            name='field',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
