# Generated by Django 3.2.17 on 2023-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_submissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlog',
            name='assignment',
            field=models.CharField(max_length=128, verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='course',
            field=models.CharField(max_length=128, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='course',
            field=models.CharField(max_length=128, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='student',
            field=models.CharField(max_length=128, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='submission',
            field=models.CharField(max_length=128, verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
