# Generated by Django 3.2.17 on 2023-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20230207_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
