# Generated by Django 3.2.17 on 2023-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_assignmentlog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentlog',
            name='type',
        ),
    ]
