# Generated by Django 3.2.18 on 2023-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_remove_assignmentlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlog',
            name='assignment',
            field=models.CharField(max_length=500, verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='submissionlog',
            name='submission',
            field=models.CharField(max_length=500, verbose_name='Assignment'),
        ),
    ]
