# Generated by Django 3.2.20 on 2023-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_auto_20230606_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentlog',
            name='from_value',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='to_value',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
