# Generated by Django 3.2.16 on 2023-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=128)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_title', models.CharField(max_length=128)),
            ],
        ),
    ]
