# Generated by Django 3.2.16 on 2023-01-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_name',
        ),
    ]
