# Generated by Django 3.2.16 on 2023-01-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_course_title_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=128)),
                ('assignment_id', models.IntegerField()),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('lock_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('needs_grading_count', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('rubric', models.IntegerField(blank=True, null=True)),
                ('anonymous_grading', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
