# Generated by Django 3.2.16 on 2023-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
