# Generated by Django 3.2.16 on 2023-01-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_assignment_assignment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='open_at',
            new_name='unlock_at',
        ),
    ]
