# Generated by Django 3.2.17 on 2023-02-02 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230202_1020'),
        ('core', '0009_course_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
    ]
