# Generated by Django 3.2.17 on 2023-02-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assignment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric',
        ),
    ]
