# Generated by Django 3.2.17 on 2023-02-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_programme_student_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programme'),
        ),
    ]
