# Generated by Django 3.2.17 on 2023-02-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assignment_pc_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pc_graded',
            field=models.FloatField(blank=True, null=True, verbose_name='Graded (%)'),
        ),
    ]
