# Generated by Django 3.2.17 on 2023-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230206_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
