# Generated by Django 3.2.17 on 2023-02-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_submission_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='graded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='not_submitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pc_graded',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Graded (%)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ungraded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
