# Generated by Django 3.2.17 on 2023-02-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230206_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='integrity_issue',
            new_name='integrity_concern',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='posted_at',
        ),
    ]
