# Generated by Django 3.2.17 on 2023-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230206_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='turnitin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
