# Generated by Django 3.2.17 on 2023-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_submission_turnitin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sas_exam',
            field=models.BooleanField(default=False, verbose_name='SAS Exam'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Flag'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(max_length=128, verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=128, unique=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sortable_name',
            field=models.CharField(max_length=128, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='integrity_concern',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Integrity Flag'),
        ),
    ]
