# Generated by Django 3.2.17 on 2023-02-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230207_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.CharField(blank=True, max_length=286, null=True),
        ),
    ]
