# Generated by Django 3.2.17 on 2023-02-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_submission_graded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rubric',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
