# Generated by Django 3.2.17 on 2023-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20230207_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('items_graded', models.IntegerField(blank=True, null=True)),
                ('courses_graded_in', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
