# Generated by Django 3.2.17 on 2023-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_staff_canvas_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='days_late',
        ),
        migrations.AddField(
            model_name='submission',
            name='seconds_late',
            field=models.IntegerField(default=0),
        ),
    ]
