# Generated by Django 3.2.17 on 2023-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230207_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='sis_user_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
