# Generated by Django 3.2.17 on 2023-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230207_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sis_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
