# Generated by Django 3.2.17 on 2023-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_submission_sis_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
