# Generated by Django 3.2.17 on 2023-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_submission_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
