# Generated by Django 3.2.18 on 2023-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='average_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Score (%)'),
        ),
    ]
