# Generated by Django 3.2.18 on 2023-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_submission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='has_overrides',
            field=models.BooleanField(default=False),
        ),
    ]
