# Generated by Django 3.2.18 on 2023-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
