# Generated by Django 3.2.18 on 2023-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20230311_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='has_overrides',
            field=models.BooleanField(default=False, verbose_name='Overrides'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Published'),
        ),
    ]
