# Generated by Django 3.2.18 on 2023-03-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230312_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marker',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='marker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='anonymous_grading',
            field=models.BooleanField(verbose_name='Anonymous Grading'),
        ),
    ]
