# Generated by Django 3.2.18 on 2023-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230321_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sas_exam',
        ),
        migrations.AddField(
            model_name='assignment',
            name='quiz',
            field=models.BooleanField(default=False, verbose_name='Quiz'),
        ),
    ]
