# Generated by Django 3.2.18 on 2023-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230526_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sas_exam',
            field=models.BooleanField(default=False, verbose_name='SAS Exam'),
        ),
    ]
