# Generated by Django 3.2.18 on 2023-06-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20230606_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resit_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.course'),
        ),
    ]
