# Generated by Django 3.2.20 on 2023-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_assignment_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points_possible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
