# Generated by Django 3.2.20 on 2023-09-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_assignment_points_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rollover_to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollover_to_course', to='core.course'),
        ),
    ]
