# Generated by Django 3.2.22 on 2023-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_assignment_previous_term_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
