# Generated by Django 3.2.22 on 2023-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active Flag'),
        ),
    ]
