# Generated by Django 3.2.22 on 2023-11-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_course_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='support_plan',
            field=models.BooleanField(default=False, verbose_name='Support Plan'),
        ),
    ]
