# Generated by Django 3.2.22 on 2023-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_student_support_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='support_plan_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
