# Generated by Django 3.2.22 on 2023-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_student_support_plan_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marker_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
