# Generated by Django 3.2.22 on 2023-11-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20231115_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='support_plan_message',
            new_name='marker_message',
        ),
        migrations.AlterField(
            model_name='student',
            name='support_plan',
            field=models.BooleanField(default=False, verbose_name='SpLD'),
        ),
    ]
