# Generated by Django 3.2.23 on 2024-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20240409_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(blank=True, to='core.Programme'),
        ),
    ]
