# Generated by Django 3.2.23 on 2024-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_student_repeating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
