# Generated by Django 3.2.23 on 2024-05-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_assignment_rubric_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='gai_declaration',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='GAI Declaration'),
        ),
    ]
