# Generated by Django 3.2.23 on 2024-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_submission_gai_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='excused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
