# Generated by Django 3.2.25 on 2024-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20240706_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='excused',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
