# Generated by Django 3.2.18 on 2023-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='unlock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
