# Generated by Django 3.2.18 on 2023-03-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230312_1640'),
        ('modules', '0002_alter_module_unlock_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'course')},
        ),
    ]
