# Generated by Django 3.2.18 on 2023-03-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20230202_1455'),
        ('core', '0040_auto_20230321_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('extension_type', models.CharField(choices=[('EXTENSION', 'Extension'), ('ELP', 'Exemption from late penalty (ELP)')], default='EXTENSION', max_length=128)),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('extension_deadline', models.DateTimeField(blank=True, null=True)),
                ('original_deadline', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
        ),
    ]
