# Generated by Django 3.2.18 on 2023-03-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230321_0633'),
        ('accounts', '0005_auto_20230202_1455'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='apply_to_subcomponents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='approved_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='course',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.course'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='original_deadline',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='unique_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
