# Generated by Django 3.2.18 on 2023-05-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230202_1455'),
        ('core', '0041_auto_20230526_0502'),
        ('extensions', '0002_auto_20230322_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='approved',
            field=models.BooleanField(default=False, editable=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile', verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Student'),
        ),
    ]
