# Generated by Django 3.2.18 on 2023-06-27 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_auto_20230613_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='confirmation_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
