# Generated by Django 3.2.18 on 2023-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0006_extension_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
