# Generated by Django 3.2.18 on 2023-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension_type',
            field=models.CharField(choices=[('EXTENSION', 'Extension'), ('ELP', 'Exemption from late penalty (ELP)')], default='ELP', max_length=128),
        ),
        migrations.AlterField(
            model_name='extension',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='extensions/', verbose_name='Evidence upload'),
        ),
    ]
