# Generated by Django 3.2.20 on 2023-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0009_extension_late_ignore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='extensions/evidence', verbose_name='Evidence upload'),
        ),
    ]
