# Generated by Django 3.2.22 on 2023-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0010_alter_extension_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='confirm_self_certified',
            field=models.BooleanField(default=False, verbose_name='I confirm I understand that if I choose to submit this form without evidence my application will be considered as one of two self-certified ELPs available to me during this assessment period.'),
        ),
    ]
