# Generated by Django 3.2.23 on 2024-03-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0013_extension_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
