# Generated by Django 3.2.25 on 2025-01-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0015_extension_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='extension_length',
            field=models.IntegerField(default=8, help_text='Extension length in days.'),
        ),
    ]
