# Generated by Django 3.2.25 on 2025-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0017_date_elp_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='submission_window',
            field=models.IntegerField(default=15, help_text='Submission window in days.'),
        ),
        migrations.AlterField(
            model_name='date',
            name='extension_length',
            field=models.IntegerField(default=7, help_text='Extension length in days.'),
        ),
    ]
